server:
  port: 8103

spring:
  application:
    name: park-energy-platform
  datasource:
    url: ${PARK_DB_URL:jdbc:mysql://115.159.222.238:3306/park_energy_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true}
    username: admin
    password: 'Saki#Mygo06'
    driver-class-name: com.mysql.cj.jdbc.Driver

park:
  platform:
    data-base-url: ${PARK_DATA_BASE_URL:http://localhost:8102}
    access-base-url: ${PARK_ACCESS_BASE_URL:http://localhost:8101}

sa-token:
  token-name: Authorization
  token-prefix: Bearer
  timeout: 86400
  active-timeout: -1
  is-concurrent: true
  is-share: true
  is-log: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
